[MALTA_0]
coordinates = "cartesian"
mask_file = "/home/hinata/MALTA2/Ready_June/config/3malta_ref_30tilt/output/MaskCreator/MALTA_0/mask_MALTA_0.txt"
material_budget = 0.00106768
number_of_pixels = 224, 512
orientation = -0.216177deg,-0.152292deg,0.0759742deg
orientation_mode = "xyz"
pixel_pitch = 36.4um,36.4um
position = 0.004um,-0.506um,-50.8mm
role = "reference"
spatial_resolution = 10.5um,10.5um
time_resolution = 5ns
type = "malta2"

[MALTA_1]
coordinates = "cartesian"
mask_file = "/home/hinata/MALTA2/Ready_June/config/3malta_ref_30tilt/output/MaskCreator/MALTA_1/mask_MALTA_1.txt"
material_budget = 0.00106768
number_of_pixels = 224, 512
orientation = -0.115852deg,-30deg,-0.200707deg
orientation_mode = "xyz"
pixel_pitch = 36.4um,36.4um
position = 146.142um,-92.96um,0um
spatial_resolution = 10.5um,10.5um
time_resolution = 5ns
type = "malta2"

[MALTA_2]
coordinates = "cartesian"
mask_file = "/home/hinata/MALTA2/Ready_June/config/3malta_ref_30tilt/output/MaskCreator/MALTA_2/mask_MALTA_2.txt"
material_budget = 0.00106768
number_of_pixels = 224, 512
orientation = 0.332029deg,0.152292deg,0.124676deg
orientation_mode = "xyz"
pixel_pitch = 36.4um,36.4um
position = -178.217um,123.959um,76.2mm
spatial_resolution = 10.5um,10.5um
time_resolution = 5ns
type = "malta2"

