[MALTA_0]
coordinates = "cartesian"
mask_file = "/home/hinata/MALTA2/Ready_June/config/3malta_ref/output/MaskCreator/MALTA_0/mask_MALTA_0.txt"
material_budget = 0.00106768
number_of_pixels = 224, 512
orientation = 0.00721927deg,0.00263561deg,-0.0148969deg
orientation_mode = "xyz"
pixel_pitch = 36.4um,36.4um
position = -0.219um,0.121um,-25.4mm
role = "reference"
spatial_resolution = 10.5um,10.5um
time_resolution = 5ns
type = "malta2"

[MALTA_1]
coordinates = "cartesian"
mask_file = "/home/hinata/MALTA2/Ready_June/config/3malta_ref/output/MaskCreator/MALTA_1/mask_MALTA_1.txt"
material_budget = 0.00106768
number_of_pixels = 224, 512
orientation = 0.000744845deg,-0.000171887deg,0.266311deg
orientation_mode = "xyz"
pixel_pitch = 36.4um,36.4um
position = 120.935um,-85.415um,0um
spatial_resolution = 10.5um,10.5um
time_resolution = 5ns
type = "malta2"

[MALTA_2]
coordinates = "cartesian"
mask_file = "/home/hinata/MALTA2/Ready_June/config/3malta_ref/output/MaskCreator/MALTA_2/mask_MALTA_2.txt"
material_budget = 0.00106768
number_of_pixels = 224, 512
orientation = -0.00796411deg,-0.00246372deg,-0.251414deg
orientation_mode = "xyz"
pixel_pitch = 36.4um,36.4um
position = -208.085um,149.505um,25.4mm
spatial_resolution = 10.5um,10.5um
time_resolution = 5ns
type = "malta2"

