[MALTA_0]
coordinates = "cartesian"
mask_file = "/home/hinata/MALTA2/Ready_June/config/3malta_ref/output/MaskCreator/MALTA_0/mask_MALTA_0.txt"
material_budget = 0.00106768
number_of_pixels = 224, 512
orientation = -0.0728802deg,-0.00446907deg,-0.0440605deg
orientation_mode = "xyz"
pixel_pitch = 36.4um,36.4um
position = -0.407um,-0.017um,-25.4mm
role = "reference"
spatial_resolution = 10.5um,10.5um
time_resolution = 5ns
type = "malta2"

[MALTA_1]
coordinates = "cartesian"
mask_file = "/home/hinata/MALTA2/Ready_June/config/3malta_ref/output/MaskCreator/MALTA_1/mask_MALTA_1.txt"
material_budget = 0.00106768
number_of_pixels = 224, 512
orientation = -0.00383882deg,0.000114592deg,0.255081deg
orientation_mode = "xyz"
pixel_pitch = 36.4um,36.4um
position = 119.461um,-87.442um,0um
spatial_resolution = 10.5um,10.5um
time_resolution = 5ns
type = "malta2"

[MALTA_2]
coordinates = "cartesian"
mask_file = "/home/hinata/MALTA2/Ready_June/config/3malta_ref/output/MaskCreator/MALTA_2/mask_MALTA_2.txt"
material_budget = 0.00106768
number_of_pixels = 224, 512
orientation = 0.076719deg,0.00435448deg,-0.21102deg
orientation_mode = "xyz"
pixel_pitch = 36.4um,36.4um
position = -210.089um,145.972um,25.4mm
spatial_resolution = 10.5um,10.5um
time_resolution = 5ns
type = "malta2"

