[MALTA_0]
coordinates = "cartesian"
mask_file = "/home/hinata/MALTA2/Ready_June/config/3malta_ref_60tilt/output/MaskCreator/MALTA_0/mask_MALTA_0.txt"
material_budget = 0.00106768
number_of_pixels = 224, 512
orientation = -0deg,0deg,-0deg
orientation_mode = "xyz"
pixel_pitch = 36.4um,36.4um
position = 0um,0um,-50.8mm
role = "reference"
spatial_resolution = 10.5um,10.5um
time_resolution = 5ns
type = "malta2"

[MALTA_1]
coordinates = "cartesian"
mask_file = "/home/hinata/MALTA2/Ready_June/config/3malta_ref_60tilt/output/MaskCreator/MALTA_1/mask_MALTA_1.txt"
material_budget = 0.00106768
number_of_pixels = 224, 512
orientation = -0deg,-60deg,-0deg
orientation_mode = "xyz"
pixel_pitch = 36.4um,36.4um
position = 0um,0um,0um
spatial_resolution = 10.5um,10.5um
time_resolution = 5ns
type = "malta2"

[MALTA_2]
coordinates = "cartesian"
mask_file = "/home/hinata/MALTA2/Ready_June/config/3malta_ref_60tilt/output/MaskCreator/MALTA_2/mask_MALTA_2.txt"
material_budget = 0.00106768
number_of_pixels = 224, 512
orientation = -0deg,0deg,-0deg
orientation_mode = "xyz"
pixel_pitch = 36.4um,36.4um
position = 0um,0um,101.6mm
spatial_resolution = 10.5um,10.5um
time_resolution = 5ns
type = "malta2"

