[MALTA_0]
coordinates = "cartesian"
mask_file = "/home/hinata/MALTA2/Ready_June/config/3malta_ref_60tilt/output/MaskCreator/MALTA_0/mask_MALTA_0.txt"
material_budget = 0.00106768
number_of_pixels = 224, 512
orientation = -0.0876625deg,-0.970533deg,-1.31534deg
orientation_mode = "xyz"
pixel_pitch = 36.4um,36.4um
position = 1.03um,1.475um,-50.8mm
role = "reference"
spatial_resolution = 10.5um,10.5um
time_resolution = 5ns
type = "malta2"

[MALTA_1]
coordinates = "cartesian"
mask_file = "/home/hinata/MALTA2/Ready_June/config/3malta_ref_60tilt/output/MaskCreator/MALTA_1/mask_MALTA_1.txt"
material_budget = 0.00106768
number_of_pixels = 224, 512
orientation = -0.289deg,-59.9165deg,-0.169939deg
orientation_mode = "xyz"
pixel_pitch = 36.4um,36.4um
position = 144.021um,-89.182um,0um
spatial_resolution = 10.5um,10.5um
time_resolution = 5ns
type = "malta2"

[MALTA_2]
coordinates = "cartesian"
mask_file = "/home/hinata/MALTA2/Ready_June/config/3malta_ref_60tilt/output/MaskCreator/MALTA_2/mask_MALTA_2.txt"
material_budget = 0.00106768
number_of_pixels = 224, 512
orientation = 0.376662deg,0.887053deg,1.48528deg
orientation_mode = "xyz"
pixel_pitch = 36.4um,36.4um
position = -184.14um,127.361um,101.6mm
spatial_resolution = 10.5um,10.5um
time_resolution = 5ns
type = "malta2"

