[MALTA_0]
coordinates = "cartesian"
mask_file = "/home/hinata/MALTA2/Ready_June/config/3malta_ref/output/MaskCreator/MALTA_0/mask_MALTA_0.txt"
material_budget = 0.00106768
number_of_pixels = 224, 512
orientation = -0.00882355deg,-0.133958deg,-0.424906deg
orientation_mode = "xyz"
pixel_pitch = 36.4um,36.4um
position = 0.065um,-0.118um,-25.4mm
role = "reference"
spatial_resolution = 10.5um,10.5um
time_resolution = 5ns
type = "malta2"

[MALTA_1]
coordinates = "cartesian"
mask_file = "/home/hinata/MALTA2/Ready_June/config/3malta_ref/output/MaskCreator/MALTA_1/mask_MALTA_1.txt"
material_budget = 0.00106768
number_of_pixels = 224, 512
orientation = 0.00550039deg,0.00292208deg,0.276108deg
orientation_mode = "xyz"
pixel_pitch = 36.4um,36.4um
position = 120.599um,-82.309um,0um
spatial_resolution = 10.5um,10.5um
time_resolution = 5ns
type = "malta2"

[MALTA_2]
coordinates = "cartesian"
mask_file = "/home/hinata/MALTA2/Ready_June/config/3malta_ref/output/MaskCreator/MALTA_2/mask_MALTA_2.txt"
material_budget = 0.00106768
number_of_pixels = 224, 512
orientation = 0.00338045deg,0.131035deg,0.148797deg
orientation_mode = "xyz"
pixel_pitch = 36.4um,36.4um
position = -208.825um,152.999um,25.4mm
spatial_resolution = 10.5um,10.5um
time_resolution = 5ns
type = "malta2"

