[MALTA_0]
coordinates = "cartesian"
mask_file = "/home/hinata/MALTA2/Ready_June/config/2malta_dut/output/MaskCreator/MALTA_0/mask_MALTA_0.txt"
material_budget = 0.00106768
number_of_pixels = 224, 512
orientation = 0.0027502deg,0.0339764deg,-0.0234913deg
orientation_mode = "xyz"
pixel_pitch = 36.4um,36.4um
position = -0.167um,0.926um,-25.4mm
role = "reference"
spatial_resolution = 10.5um,10.5um
time_resolution = 5ns
type = "malta2"

[MALTA_1]
coordinates = "cartesian"
mask_file = "/home/hinata/MALTA2/Ready_June/config/2malta_dut/output/MaskCreator/MALTA_1/mask_MALTA_1.txt"
material_budget = 0.00106768
number_of_pixels = 224, 512
orientation = 0.000974028deg,-0.00578687deg,0.370532deg
orientation_mode = "xyz"
pixel_pitch = 36.4um,36.4um
position = 119.755um,-87.985um,0um
role = "dut"
spatial_resolution = 10.5um,10.5um
time_resolution = 5ns
type = "malta2"

[MALTA_2]
coordinates = "cartesian"
mask_file = "/home/hinata/MALTA2/Ready_June/config/2malta_dut/output/MaskCreator/MALTA_2/mask_MALTA_2.txt"
material_budget = 0.00106768
number_of_pixels = 224, 512
orientation = -0.00372423deg,-0.0281895deg,-0.347041deg
orientation_mode = "xyz"
pixel_pitch = 36.4um,36.4um
position = -210.438um,142.955um,25.4mm
spatial_resolution = 10.5um,10.5um
time_resolution = 5ns
type = "malta2"

