[MALTA_0]
coordinates = "cartesian"
mask_file = "/home/hinata/MALTA2/Ready_June/config/2malta_dut/output/MaskCreator/MALTA_0/mask_MALTA_0.txt"
material_budget = 0.00106768
number_of_pixels = 512, 224
orientation = 0.375631deg,0.397518deg,-0.330367deg
orientation_mode = "xyz"
pixel_pitch = 36.4um,36.4um
position = 2.235um,4.717um,-25.4mm
role = "reference"
spatial_resolution = 10.5um,10.5um
time_resolution = 5ns
type = "malta2"

[MALTA_1]
coordinates = "cartesian"
mask_file = "/home/hinata/MALTA2/Ready_June/config/2malta_dut/output/MaskCreator/MALTA_1/mask_MALTA_1.txt"
material_budget = 0.00106768
number_of_pixels = 512, 224
orientation = 0.00469825deg,-0.0054431deg,0.291063deg
orientation_mode = "xyz"
pixel_pitch = 36.4um,36.4um
position = -246.464um,-393.629um,0um
role = "dut"
spatial_resolution = 10.5um,10.5um
time_resolution = 5ns
type = "malta2"

[MALTA_2]
coordinates = "cartesian"
mask_file = "/home/hinata/MALTA2/Ready_June/config/2malta_dut/output/MaskCreator/MALTA_2/mask_MALTA_2.txt"
material_budget = 0.00106768
number_of_pixels = 512, 224
orientation = -0.380329deg,-0.392075deg,0.0393049deg
orientation_mode = "xyz"
pixel_pitch = 36.4um,36.4um
position = -291.114um,724.025um,25.4mm
spatial_resolution = 10.5um,10.5um
time_resolution = 5ns
type = "malta2"

