[MALTA_0]
coordinates = "cartesian"
mask_file = "/home/hinata/MALTA2/Ready_June/config/2malta_dut/output/MaskCreator/MALTA_0/mask_MALTA_0.txt"
material_budget = 0.00106768
number_of_pixels = 224, 512
orientation = -0.0160428deg,0.0312835deg,-0.0136937deg
orientation_mode = "xyz"
pixel_pitch = 36.4um,36.4um
position = -0.496um,-0.163um,-25.4mm
role = "reference"
spatial_resolution = 10.5um,10.5um
time_resolution = 5ns
type = "malta2"

[MALTA_1]
coordinates = "cartesian"
mask_file = "/home/hinata/MALTA2/Ready_June/config/2malta_dut/output/MaskCreator/MALTA_1/mask_MALTA_1.txt"
material_budget = 0.00106768
number_of_pixels = 224, 512
orientation = 0.000859437deg,-0.00509932deg,0.370475deg
orientation_mode = "xyz"
pixel_pitch = 36.4um,36.4um
position = 119.639um,-87.149um,0um
role = "dut"
spatial_resolution = 10.5um,10.5um
time_resolution = 5ns
type = "malta2"

[MALTA_2]
coordinates = "cartesian"
mask_file = "/home/hinata/MALTA2/Ready_June/config/2malta_dut/output/MaskCreator/MALTA_2/mask_MALTA_2.txt"
material_budget = 0.00106768
number_of_pixels = 224, 512
orientation = 0.0151834deg,-0.0261842deg,-0.356781deg
orientation_mode = "xyz"
pixel_pitch = 36.4um,36.4um
position = -210.178um,145.826um,25.4mm
spatial_resolution = 10.5um,10.5um
time_resolution = 5ns
type = "malta2"

