[Corryvreckan]
#log_level  = "INFO"
log_format = "DEFAULT"
workers = 1
log_file = "../output/debug_log.txt"

detectors_file = "../../geometry/lab_test/3malta_init.conf"
output_directory = "../output"
histogram_file = "lab_check.root"
number_of_events = -1

[EventLoaderMALTA]
detector_names = "MALTA_0", "MALTA_1", "MALTA_2"
base_path = "/path/to/MaltaDAQ/output" # MaltaMultiDAQ の -o で指定したディレクトリ
run_number = 1                          # MaltaMultiDAQ の -r で指定したrun番号
online_mode = true
real_data = true

[ClusteringSpatial]
use_trigger_timestamp = true

[Correlations]

[AnalysisEfficiency]

[AnalysisTracks]

[Tracking4D]
track_model = "straightline"
require_detectors = "MALTA_0", "MALTA_1", "MALTA_2"
min_hits_on_track = 2
time_cut_abs = 10ns
exclude_dut = true
spatial_cut_abs = 100um, 100um
reject_by_roi = true

[OnlineMonitor]
update = 10
canvas_title = "MALTA2 DUT Telescope Online Monitor"
clustering_module = "ClusteringSpatial"
tracking_module = "Tracking4D"
ignore_aux = true
#influxdb_url   = "http://localhost:8086"
#influxdb_token = "malta-monitor-token"
#auto_save_dir  = "/home/hinata/MALTA2/Ready_June/grafana-monitor/snapshots/"

correlation_x2d = [["Correlations/%DETECTOR%/correlationX_2Dlocal", "colz"]]
correlation_y2d = [["Correlations/%DETECTOR%/correlationY_2Dlocal", "colz"]]

dut_plots = [
    ["ClusteringSpatial/%DUT%/clusterPositionLocal", "colz"],
    ["ClusteringSpatial/%DUT%/clusterSize"],
    ["AnalysisDUT/%DUT%/clusterChargeAssociated"],
    ["AnalysisDUT/%DUT%/associatedTracksVersusTime"],
    ["AnalysisEfficiency/%DUT%/pixelEfficiency", "colz"]
]


