[Corryvreckan]
log_level  = "INFO"
log_format = "DEFAULT"
detectors_file = "@GEOM_IN@"
histogram_file = "allaligncheck_run@RUN@.root"
number_of_events = -1

[EventLoaderMALTA]
detector_names = "MALTA_0", "MALTA_1", "MALTA_2"
base_path = "/home/hinata/MALTA2/JunBeamTest/sim/output"
run_number = @RUN@

[ClusteringSpatial]
charge_weighting = false
reject_by_roi = false

[FilterEvents]
max_clusters_per_plane = 3

[Correlations]

[Tracking4D]
track_model = "straightline"
require_detectors = "MALTA_0", "MALTA_1", "MALTA_2"
min_hits_on_track = 3
exclude_dut = false
