# Allpix Squared detector geometry - https://cern.ch/allpix-squared

[MALTA_0]
coordinates = "cartesian"
position = 0mm, 0mm, -50.8mm #ここをラボと同じ状況にしてください
orientation_mode = "xyz"
orientation = -0deg, 0deg, -0deg
type = "MALTA2"
pixel_pitch = 36.4um, 36.4um
number_of_pixels = 224, 512
spatial_resolution = 10.5um, 10.5um
time_resolution = 5ns
role = reference
material_budget = 0.00106768

[MALTA_1]
coordinates = "cartesian"
position = 0mm, 0mm, 0mm #ここもラボと同じ状況に
orientation_mode = "xyz"
orientation = -0deg, -0deg, -0deg
type = "MALTA2"
pixel_pitch = 36.4um, 36.4um
number_of_pixels = 224, 512
spatial_resolution = 10.5um, 10.5um
time_resolution = 5ns
role = dut
material_budget = 0.00106768

[MALTA_2]
coordinates = "cartesian"
position = 0mm, 0mm, 76.2mm#ここもラボと同じ状況に
orientation_mode = "xyz"
orientation = -0deg, 0deg, -0deg
type = "MALTA2"
pixel_pitch = 36.4um, 36.4um
number_of_pixels = 224, 512
spatial_resolution = 10.5um, 10.5um
time_resolution = 5ns
material_budget = 0.00106768

